version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  database:
    build: ./database
    container_name: database_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:

volumes:
  db_data:
